# Generated by Django 6.0.4 on 2026-04-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productimage_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, unique=True, verbose_name='Объем памяти')),
            ],
            options={
                'verbose_name': 'Оперативная память',
                'verbose_name_plural': 'Оперативная память',
                'ordering': ['label'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='memory_options',
            field=models.ManyToManyField(blank=True, to='products.memoryoption', verbose_name='Оперативная память'),
        ),
    ]
