# Generated by Django 6.0.4 on 2026-04-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_memoryoption_product_memory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memoryoption',
            options={'ordering': ['label'], 'verbose_name': 'Внутренняя память', 'verbose_name_plural': 'Внутренняя память'},
        ),
        migrations.AlterField(
            model_name='memoryoption',
            name='label',
            field=models.CharField(max_length=50, unique=True, verbose_name='Объем внутренней памяти'),
        ),
        migrations.AlterField(
            model_name='product',
            name='memory_options',
            field=models.ManyToManyField(blank=True, to='products.memoryoption', verbose_name='Внутренняя память'),
        ),
    ]
