# Generated by Django 6.0.4 on 2026-04-25 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_memoryoption_options_alter_memoryoption_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMemoryPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Старая цена')),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='products.memoryoption')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_prices', to='products.product')),
            ],
            options={
                'verbose_name': 'Цена по памяти',
                'verbose_name_plural': 'Цены по памяти',
                'unique_together': {('product', 'memory')},
            },
        ),
    ]
