# Generated by Django 6.0.4 on 2026-04-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productmemoryprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseSizeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, unique=True, verbose_name='Размер корпуса')),
            ],
            options={
                'verbose_name': 'Размер корпуса',
                'verbose_name_plural': 'Размеры корпуса',
                'ordering': ['label'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='case_size_options',
            field=models.ManyToManyField(blank=True, to='products.casesizeoption', verbose_name='Размеры корпуса'),
        ),
    ]
