# Generated by Django 6.0.4 on 2026-04-26 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_casesizeoption_product_case_size_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCaseSizePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Старая цена')),
                ('case_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='products.casesizeoption')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_size_prices', to='products.product')),
            ],
            options={
                'verbose_name': 'Цена по размеру корпуса',
                'verbose_name_plural': 'Цены по размеру корпуса',
                'unique_together': {('product', 'case_size')},
            },
        ),
    ]
