# Generated by Django 6.0.4 on 2026-04-27 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productcasesizeprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренди'},
        ),
        migrations.AlterModelOptions(
            name='casesizeoption',
            options={'ordering': ['label'], 'verbose_name': 'Размір корпуса', 'verbose_name_plural': 'Разміри корпуса'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Колір', 'verbose_name_plural': 'Кольори'},
        ),
        migrations.AlterModelOptions(
            name='memoryoption',
            options={'ordering': ['label'], 'verbose_name': "Внутрішня пам'ять", 'verbose_name_plural': "Внутрішня пам'ять"},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товари'},
        ),
        migrations.AlterModelOptions(
            name='productcasesizeprice',
            options={'verbose_name': 'Ціна по розміру корпуса', 'verbose_name_plural': 'Ціни по розміру корпуса'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Зображення', 'verbose_name_plural': 'Зображення'},
        ),
        migrations.AlterModelOptions(
            name='productmemoryprice',
            options={'verbose_name': "Ціна по пам'яті", 'verbose_name_plural': "Ціни по пам'яті"},
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='casesizeoption',
            name='label',
            field=models.CharField(max_length=50, unique=True, verbose_name='Размір корпуса'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='memoryoption',
            name='label',
            field=models.CharField(max_length=50, unique=True, verbose_name="Об'єм внутрішньої пам'яті"),
        ),
        migrations.AlterField(
            model_name='product',
            name='case_size_options',
            field=models.ManyToManyField(blank=True, to='products.casesizeoption', verbose_name='Розміри корпусу'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(blank=True, to='products.color', verbose_name='Кольори'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='В наявності'),
        ),
        migrations.AlterField(
            model_name='product',
            name='memory_options',
            field=models.ManyToManyField(blank=True, to='products.memoryoption', verbose_name="Внутрішня пам'ять"),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стара ціна'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='productcasesizeprice',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стара ціна'),
        ),
        migrations.AlterField(
            model_name='productcasesizeprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='productmemoryprice',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стара ціна'),
        ),
        migrations.AlterField(
            model_name='productmemoryprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='productspec',
            name='value',
            field=models.CharField(max_length=200, verbose_name='Значення'),
        ),
    ]
