# Generated by Django 6.0.4 on 2026-04-28 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_brand_options_alter_casesizeoption_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenSizeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, unique=True, verbose_name='Діагональ екрана')),
            ],
            options={
                'verbose_name': 'Діагональ екрана',
                'verbose_name_plural': 'Діагоналі екрана',
                'ordering': ['label'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='screen_size_options',
            field=models.ManyToManyField(blank=True, to='products.screensizeoption', verbose_name='Діагональ екрана'),
        ),
        migrations.CreateModel(
            name='ProductScreenSizePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стара ціна')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_size_prices', to='products.product')),
                ('screen_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='products.screensizeoption')),
            ],
            options={
                'verbose_name': 'Ціна по діагоналі екрана',
                'verbose_name_plural': 'Ціни по діагоналі екрана',
                'unique_together': {('product', 'screen_size')},
            },
        ),
    ]
