# Generated by Django 6.0.4 on 2026-04-25 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_cart_options_alter_cartitem_options_and_more'),
        ('products', '0005_memoryoption_product_memory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='memory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.memoryoption'),
        ),
    ]
