# Generated by Django 6.0.4 on 2026-04-26 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_color_orderitem_memory'),
        ('products', '0008_casesizeoption_product_case_size_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='case_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.casesizeoption'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='case_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.casesizeoption'),
        ),
    ]
