# Generated by Django 6.0.4 on 2026-04-28 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_cart_options_alter_cartitem_options_and_more'),
        ('products', '0011_screensizeoption_product_screen_size_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='screen_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.screensizeoption'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='screen_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.screensizeoption'),
        ),
    ]
