# Generated by Django 6.0.4 on 2026-04-26 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_wishlist_unique_together_wishlist_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адрес доставки'),
        ),
    ]
