# Generated by Django 6.0.4 on 2026-04-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='cons',
            field=models.TextField(blank=True, verbose_name='Минусы'),
        ),
        migrations.AddField(
            model_name='review',
            name='pros',
            field=models.TextField(blank=True, verbose_name='Плюсы'),
        ),
    ]
