# Generated by Django 6.0.4 on 2026-04-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_cons_review_pros'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Відгук', 'verbose_name_plural': 'Відгуки'},
        ),
        migrations.AlterField(
            model_name='review',
            name='cons',
            field=models.TextField(blank=True, verbose_name='Мінуси'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Схвалений'),
        ),
        migrations.AlterField(
            model_name='review',
            name='pros',
            field=models.TextField(blank=True, verbose_name='Плюси'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(verbose_name='Текст відгуку'),
        ),
    ]
